update=9/7/2018 1:13:10 AM
version=1
last_client=kicad
[pcbnew]
version=1
LastNetListRead=
UseCmpFile=1
PadDrill=0.600000000000
PadDrillOvalY=0.600000000000
PadSizeH=1.500000000000
PadSizeV=1.500000000000
PcbTextSizeV=1.500000000000
PcbTextSizeH=1.500000000000
PcbTextThickness=0.300000000000
ModuleTextSizeV=1.000000000000
ModuleTextSizeH=1.000000000000
ModuleTextSizeThickness=0.150000000000
SolderMaskClearance=0.000000000000
SolderMaskMinWidth=0.000000000000
DrawSegmentWidth=0.200000000000
BoardOutlineThickness=0.100000000000
ModuleOutlineThickness=0.150000000000
[cvpcb]
version=1
NetIExt=net
[general]
version=1
[eeschema]
version=1
LibDir=
[eeschema/libraries]
LibName1=power
LibName2=device
LibName3=switches
LibName4=relays
LibName5=motors
LibName6=transistors
LibName7=conn
LibName8=linear
LibName9=regul
LibName10=74xx
LibName11=cmos4000
LibName12=adc-dac
LibName13=memory
LibName14=xilinx
LibName15=microcontrollers
LibName16=dsp
LibName17=microchip
LibName18=analog_switches
LibName19=motorola
LibName20=texas
LibName21=intel
LibName22=audio
LibName23=interface
LibName24=digital-audio
LibName25=philips
LibName26=display
LibName27=cypress
LibName28=siliconi
LibName29=opto
LibName30=atmel
LibName31=contrib
LibName32=valves
LibName33=G:/softwares/KI CAD/KiCad/share/kicad/library/MCU_Microchip_PIC18
LibName34=G:/softwares/KI CAD/KiCad/share/kicad/library/4xxx
LibName35=G:/softwares/KI CAD/KiCad/share/kicad/library/4xxx_IEEE
LibName36=G:/softwares/KI CAD/KiCad/share/kicad/library/74xgxx
LibName37=G:/softwares/KI CAD/KiCad/share/kicad/library/74xx
LibName38=G:/softwares/KI CAD/KiCad/share/kicad/library/74xx_IEEE
LibName39=G:/softwares/KI CAD/KiCad/share/kicad/library/ac-dc
LibName40=G:/softwares/KI CAD/KiCad/share/kicad/library/actel
LibName41=G:/softwares/KI CAD/KiCad/share/kicad/library/adc-dac
LibName42=G:/softwares/KI CAD/KiCad/share/kicad/library/allegro
LibName43=G:/softwares/KI CAD/KiCad/share/kicad/library/Altera
LibName44=G:/softwares/KI CAD/KiCad/share/kicad/library/Amplifier_Audio
LibName45=G:/softwares/KI CAD/KiCad/share/kicad/library/Amplifier_Buffer
LibName46=G:/softwares/KI CAD/KiCad/share/kicad/library/Amplifier_Current
LibName47=G:/softwares/KI CAD/KiCad/share/kicad/library/Amplifier_Difference
LibName48=G:/softwares/KI CAD/KiCad/share/kicad/library/Amplifier_Instrumentation
LibName49=G:/softwares/KI CAD/KiCad/share/kicad/library/Amplifier_Operational
LibName50=G:/softwares/KI CAD/KiCad/share/kicad/library/Amplifier_Video
LibName51=G:/softwares/KI CAD/KiCad/share/kicad/library/Analog
LibName52=G:/softwares/KI CAD/KiCad/share/kicad/library/Analog_ADC
LibName53=G:/softwares/KI CAD/KiCad/share/kicad/library/Analog_DAC
LibName54=G:/softwares/KI CAD/KiCad/share/kicad/library/analog_devices
LibName55=G:/softwares/KI CAD/KiCad/share/kicad/library/Analog_Switch
LibName56=G:/softwares/KI CAD/KiCad/share/kicad/library/analog_switches
LibName57=G:/softwares/KI CAD/KiCad/share/kicad/library/arduino
LibName58=G:/softwares/KI CAD/KiCad/share/kicad/library/atmel
LibName59=G:/softwares/KI CAD/KiCad/share/kicad/library/audio
LibName60=G:/softwares/KI CAD/KiCad/share/kicad/library/battery_management
LibName61=G:/softwares/KI CAD/KiCad/share/kicad/library/bbd
LibName62=G:/softwares/KI CAD/KiCad/share/kicad/library/bosch
LibName63=G:/softwares/KI CAD/KiCad/share/kicad/library/brooktre
LibName64=G:/softwares/KI CAD/KiCad/share/kicad/library/cmos_ieee
LibName65=G:/softwares/KI CAD/KiCad/share/kicad/library/cmos4000
LibName66=G:/softwares/KI CAD/KiCad/share/kicad/library/Comparator
LibName67=G:/softwares/KI CAD/KiCad/share/kicad/library/conn
LibName68=G:/softwares/KI CAD/KiCad/share/kicad/library/Connector
LibName69=G:/softwares/KI CAD/KiCad/share/kicad/library/Connector_Generic
LibName70=G:/softwares/KI CAD/KiCad/share/kicad/library/Connector_Generic_MountingPin
LibName71=G:/softwares/KI CAD/KiCad/share/kicad/library/Connector_Generic_Shielded
LibName72=G:/softwares/KI CAD/KiCad/share/kicad/library/contrib
LibName73=G:/softwares/KI CAD/KiCad/share/kicad/library/Converter_ACDC
LibName74=G:/softwares/KI CAD/KiCad/share/kicad/library/Converter_DCDC
LibName75=G:/softwares/KI CAD/KiCad/share/kicad/library/CPLD_Altera
LibName76=G:/softwares/KI CAD/KiCad/share/kicad/library/CPLD_Xilinx
LibName77=G:/softwares/KI CAD/KiCad/share/kicad/library/CPU
LibName78=G:/softwares/KI CAD/KiCad/share/kicad/library/CPU_NXP_6800
LibName79=G:/softwares/KI CAD/KiCad/share/kicad/library/CPU_NXP_68000
LibName80=G:/softwares/KI CAD/KiCad/share/kicad/library/CPU_PowerPC
LibName81=G:/softwares/KI CAD/KiCad/share/kicad/library/cypress
LibName82=G:/softwares/KI CAD/KiCad/share/kicad/library/dc-dc
LibName83=G:/softwares/KI CAD/KiCad/share/kicad/library/device
LibName84=G:/softwares/KI CAD/KiCad/share/kicad/library/digital-audio
LibName85=G:/softwares/KI CAD/KiCad/share/kicad/library/diode
LibName86=G:/softwares/KI CAD/KiCad/share/kicad/library/Diode_Bridge
LibName87=G:/softwares/KI CAD/KiCad/share/kicad/library/Diode_Laser
LibName88=G:/softwares/KI CAD/KiCad/share/kicad/library/display
LibName89=G:/softwares/KI CAD/KiCad/share/kicad/library/Display_Character
LibName90=G:/softwares/KI CAD/KiCad/share/kicad/library/Display_Graphic
LibName91=G:/softwares/KI CAD/KiCad/share/kicad/library/Driver_Display
LibName92=G:/softwares/KI CAD/KiCad/share/kicad/library/Driver_FET
LibName93=G:/softwares/KI CAD/KiCad/share/kicad/library/Driver_LED
LibName94=G:/softwares/KI CAD/KiCad/share/kicad/library/Driver_Motor
LibName95=G:/softwares/KI CAD/KiCad/share/kicad/library/Driver_Relay
LibName96=G:/softwares/KI CAD/KiCad/share/kicad/library/dsp
LibName97=G:/softwares/KI CAD/KiCad/share/kicad/library/DSP_AnalogDevices
LibName98=G:/softwares/KI CAD/KiCad/share/kicad/library/DSP_Freescale
LibName99=G:/softwares/KI CAD/KiCad/share/kicad/library/DSP_Microchip_DSPIC33
LibName100=G:/softwares/KI CAD/KiCad/share/kicad/library/DSP_Motorola
LibName101=G:/softwares/KI CAD/KiCad/share/kicad/library/DSP_Texas
LibName102=G:/softwares/KI CAD/KiCad/share/kicad/library/elec-unifil
LibName103=G:/softwares/KI CAD/KiCad/share/kicad/library/ESD_Protection
LibName104=G:/softwares/KI CAD/KiCad/share/kicad/library/Filter
LibName105=G:/softwares/KI CAD/KiCad/share/kicad/library/FPGA_Lattice
LibName106=G:/softwares/KI CAD/KiCad/share/kicad/library/FPGA_Microsemi
LibName107=G:/softwares/KI CAD/KiCad/share/kicad/library/FPGA_Xilinx
LibName108=G:/softwares/KI CAD/KiCad/share/kicad/library/FPGA_Xilinx_Artix7
LibName109=G:/softwares/KI CAD/KiCad/share/kicad/library/FPGA_Xilinx_Kintex7
LibName110=G:/softwares/KI CAD/KiCad/share/kicad/library/FPGA_Xilinx_Spartan6
LibName111=G:/softwares/KI CAD/KiCad/share/kicad/library/FPGA_Xilinx_Virtex5
LibName112=G:/softwares/KI CAD/KiCad/share/kicad/library/FPGA_Xilinx_Virtex6
LibName113=G:/softwares/KI CAD/KiCad/share/kicad/library/FPGA_Xilinx_Virtex7
LibName114=G:/softwares/KI CAD/KiCad/share/kicad/library/ftdi
LibName115=G:/softwares/KI CAD/KiCad/share/kicad/library/gennum
LibName116=G:/softwares/KI CAD/KiCad/share/kicad/library/GPU
LibName117=G:/softwares/KI CAD/KiCad/share/kicad/library/Graphic
LibName118=G:/softwares/KI CAD/KiCad/share/kicad/library/graphic_symbols
LibName119=G:/softwares/KI CAD/KiCad/share/kicad/library/hc11
LibName120=G:/softwares/KI CAD/KiCad/share/kicad/library/infineon
LibName121=G:/softwares/KI CAD/KiCad/share/kicad/library/intel
LibName122=G:/softwares/KI CAD/KiCad/share/kicad/library/interface
LibName123=G:/softwares/KI CAD/KiCad/share/kicad/library/Interface_CAN_LIN
LibName124=G:/softwares/KI CAD/KiCad/share/kicad/library/Interface_CurrentLoop
LibName125=G:/softwares/KI CAD/KiCad/share/kicad/library/Interface_Ethernet
LibName126=G:/softwares/KI CAD/KiCad/share/kicad/library/Interface_Expansion
LibName127=G:/softwares/KI CAD/KiCad/share/kicad/library/Interface_HID
LibName128=G:/softwares/KI CAD/KiCad/share/kicad/library/Interface_LineDriver
LibName129=G:/softwares/KI CAD/KiCad/share/kicad/library/Interface_Optical
LibName130=G:/softwares/KI CAD/KiCad/share/kicad/library/Interface_Telecom
LibName131=G:/softwares/KI CAD/KiCad/share/kicad/library/Interface_UART
LibName132=G:/softwares/KI CAD/KiCad/share/kicad/library/Interface_USB
LibName133=G:/softwares/KI CAD/KiCad/share/kicad/library/intersil
LibName134=G:/softwares/KI CAD/KiCad/share/kicad/library/ir
LibName135=G:/softwares/KI CAD/KiCad/share/kicad/library/Isolator
LibName136=G:/softwares/KI CAD/KiCad/share/kicad/library/Isolator_Analog
LibName137=G:/softwares/KI CAD/KiCad/share/kicad/library/Jumper
LibName138=G:/softwares/KI CAD/KiCad/share/kicad/library/Lattice
LibName139=G:/softwares/KI CAD/KiCad/share/kicad/library/LED
LibName140=G:/softwares/KI CAD/KiCad/share/kicad/library/leds
LibName141=G:/softwares/KI CAD/KiCad/share/kicad/library/LEM
LibName142=G:/softwares/KI CAD/KiCad/share/kicad/library/linear
LibName143=G:/softwares/KI CAD/KiCad/share/kicad/library/Logic_LevelTranslator
LibName144=G:/softwares/KI CAD/KiCad/share/kicad/library/logic_programmable
LibName145=G:/softwares/KI CAD/KiCad/share/kicad/library/maxim
LibName146=G:/softwares/KI CAD/KiCad/share/kicad/library/MCU_AnalogDevices
LibName147=G:/softwares/KI CAD/KiCad/share/kicad/library/MCU_Cypress
LibName148=G:/softwares/KI CAD/KiCad/share/kicad/library/MCU_Espressif
LibName149=G:/softwares/KI CAD/KiCad/share/kicad/library/MCU_Intel
LibName150=G:/softwares/KI CAD/KiCad/share/kicad/library/MCU_Microchip_8051
LibName151=G:/softwares/KI CAD/KiCad/share/kicad/library/MCU_Microchip_ATmega
LibName152=G:/softwares/KI CAD/KiCad/share/kicad/library/MCU_Microchip_ATtiny
LibName153=G:/softwares/KI CAD/KiCad/share/kicad/library/MCU_Microchip_AVR
LibName154=G:/softwares/KI CAD/KiCad/share/kicad/library/MCU_Microchip_PIC10
LibName155=G:/softwares/KI CAD/KiCad/share/kicad/library/MCU_Microchip_PIC12
LibName156=G:/softwares/KI CAD/KiCad/share/kicad/library/MCU_Microchip_PIC16
LibName157=G:/softwares/KI CAD/KiCad/share/kicad/library/MCU_Microchip_PIC24
LibName158=G:/softwares/KI CAD/KiCad/share/kicad/library/MCU_Microchip_PIC32
LibName159=G:/softwares/KI CAD/KiCad/share/kicad/library/MCU_Microchip_SAME
LibName160=G:/softwares/KI CAD/KiCad/share/kicad/library/MCU_Microchip_SAML
LibName161=G:/softwares/KI CAD/KiCad/share/kicad/library/MCU_Module
LibName162=G:/softwares/KI CAD/KiCad/share/kicad/library/MCU_Nordic
LibName163=G:/softwares/KI CAD/KiCad/share/kicad/library/MCU_NXP_ColdFire
LibName164=G:/softwares/KI CAD/KiCad/share/kicad/library/MCU_NXP_HC11
LibName165=G:/softwares/KI CAD/KiCad/share/kicad/library/MCU_NXP_HC12
LibName166=G:/softwares/KI CAD/KiCad/share/kicad/library/MCU_NXP_HCS12
LibName167=G:/softwares/KI CAD/KiCad/share/kicad/library/MCU_NXP_Kinetis
LibName168=G:/softwares/KI CAD/KiCad/share/kicad/library/MCU_NXP_LPC
LibName169=G:/softwares/KI CAD/KiCad/share/kicad/library/MCU_NXP_MAC7100
LibName170=G:/softwares/KI CAD/KiCad/share/kicad/library/MCU_NXP_MCore
LibName171=G:/softwares/KI CAD/KiCad/share/kicad/library/MCU_NXP_S08
LibName172=G:/softwares/KI CAD/KiCad/share/kicad/library/MCU_Parallax
LibName173=G:/softwares/KI CAD/KiCad/share/kicad/library/MCU_SiFive
LibName174=G:/softwares/KI CAD/KiCad/share/kicad/library/MCU_SiliconLabs
LibName175=G:/softwares/KI CAD/KiCad/share/kicad/library/MCU_ST_STM8
LibName176=G:/softwares/KI CAD/KiCad/share/kicad/library/MCU_ST_STM32F0
LibName177=G:/softwares/KI CAD/KiCad/share/kicad/library/MCU_ST_STM32F1
LibName178=G:/softwares/KI CAD/KiCad/share/kicad/library/MCU_ST_STM32F2
LibName179=G:/softwares/KI CAD/KiCad/share/kicad/library/MCU_ST_STM32F3
LibName180=G:/softwares/KI CAD/KiCad/share/kicad/library/MCU_ST_STM32F4
LibName181=G:/softwares/KI CAD/KiCad/share/kicad/library/MCU_ST_STM32F7
LibName182=G:/softwares/KI CAD/KiCad/share/kicad/library/MCU_ST_STM32H7
LibName183=G:/softwares/KI CAD/KiCad/share/kicad/library/MCU_ST_STM32L0
LibName184=G:/softwares/KI CAD/KiCad/share/kicad/library/MCU_ST_STM32L1
LibName185=G:/softwares/KI CAD/KiCad/share/kicad/library/MCU_ST_STM32L4
LibName186=G:/softwares/KI CAD/KiCad/share/kicad/library/MCU_ST_STM32L4+
LibName187=G:/softwares/KI CAD/KiCad/share/kicad/library/MCU_Texas
LibName188=G:/softwares/KI CAD/KiCad/share/kicad/library/MCU_Texas_MSP430
LibName189=G:/softwares/KI CAD/KiCad/share/kicad/library/mechanical
LibName190=G:/softwares/KI CAD/KiCad/share/kicad/library/memory
LibName191=G:/softwares/KI CAD/KiCad/share/kicad/library/Memory_Controller
LibName192=G:/softwares/KI CAD/KiCad/share/kicad/library/Memory_EEPROM
LibName193=G:/softwares/KI CAD/KiCad/share/kicad/library/Memory_EPROM
LibName194=G:/softwares/KI CAD/KiCad/share/kicad/library/Memory_Flash
LibName195=G:/softwares/KI CAD/KiCad/share/kicad/library/Memory_NVRAM
LibName196=G:/softwares/KI CAD/KiCad/share/kicad/library/Memory_RAM
LibName197=G:/softwares/KI CAD/KiCad/share/kicad/library/Memory_ROM
LibName198=G:/softwares/KI CAD/KiCad/share/kicad/library/Memory_UniqueID
LibName199=G:/softwares/KI CAD/KiCad/share/kicad/library/microchip
LibName200=G:/softwares/KI CAD/KiCad/share/kicad/library/microchip_dspic33dsc
LibName201=G:/softwares/KI CAD/KiCad/share/kicad/library/microchip_pic10mcu
LibName202=G:/softwares/KI CAD/KiCad/share/kicad/library/microchip_pic12mcu
LibName203=G:/softwares/KI CAD/KiCad/share/kicad/library/microchip_pic16mcu
LibName204=G:/softwares/KI CAD/KiCad/share/kicad/library/microchip_pic18mcu
LibName205=G:/softwares/KI CAD/KiCad/share/kicad/library/microchip_pic24mcu
LibName206=G:/softwares/KI CAD/KiCad/share/kicad/library/microchip_pic32mcu
LibName207=G:/softwares/KI CAD/KiCad/share/kicad/library/microcontrollers
LibName208=G:/softwares/KI CAD/KiCad/share/kicad/library/modules
LibName209=G:/softwares/KI CAD/KiCad/share/kicad/library/Motor
LibName210=G:/softwares/KI CAD/KiCad/share/kicad/library/motor_drivers
LibName211=G:/softwares/KI CAD/KiCad/share/kicad/library/motorola
LibName212=G:/softwares/KI CAD/KiCad/share/kicad/library/motors
LibName213=G:/softwares/KI CAD/KiCad/share/kicad/library/msp430
LibName214=G:/softwares/KI CAD/KiCad/share/kicad/library/nordicsemi
LibName215=G:/softwares/KI CAD/KiCad/share/kicad/library/nxp
LibName216=G:/softwares/KI CAD/KiCad/share/kicad/library/nxp_armmcu
LibName217=G:/softwares/KI CAD/KiCad/share/kicad/library/onsemi
LibName218=G:/softwares/KI CAD/KiCad/share/kicad/library/opto
LibName219=G:/softwares/KI CAD/KiCad/share/kicad/library/Oscillator
LibName220=G:/softwares/KI CAD/KiCad/share/kicad/library/Oscillators
LibName221=G:/softwares/KI CAD/KiCad/share/kicad/library/philips
LibName222=G:/softwares/KI CAD/KiCad/share/kicad/library/PIC18F4525-I_P
LibName223=G:/softwares/KI CAD/KiCad/share/kicad/library/Potentiometer_Digital
LibName224=G:/softwares/KI CAD/KiCad/share/kicad/library/power
LibName225=G:/softwares/KI CAD/KiCad/share/kicad/library/Power_Management
LibName226=G:/softwares/KI CAD/KiCad/share/kicad/library/Power_Protection
LibName227=G:/softwares/KI CAD/KiCad/share/kicad/library/Power_Supervisor
LibName228=G:/softwares/KI CAD/KiCad/share/kicad/library/powerint
LibName229=G:/softwares/KI CAD/KiCad/share/kicad/library/pspice
LibName230=G:/softwares/KI CAD/KiCad/share/kicad/library/Reference_Current
LibName231=G:/softwares/KI CAD/KiCad/share/kicad/library/Reference_Voltage
LibName232=G:/softwares/KI CAD/KiCad/share/kicad/library/references
LibName233=G:/softwares/KI CAD/KiCad/share/kicad/library/regul
LibName234=G:/softwares/KI CAD/KiCad/share/kicad/library/Regulator_Controller
LibName235=G:/softwares/KI CAD/KiCad/share/kicad/library/Regulator_Current
LibName236=G:/softwares/KI CAD/KiCad/share/kicad/library/Regulator_Linear
LibName237=G:/softwares/KI CAD/KiCad/share/kicad/library/Regulator_SwitchedCapacitor
LibName238=G:/softwares/KI CAD/KiCad/share/kicad/library/Regulator_Switching
LibName239=G:/softwares/KI CAD/KiCad/share/kicad/library/Relay
LibName240=G:/softwares/KI CAD/KiCad/share/kicad/library/Relay_SolidState
LibName241=G:/softwares/KI CAD/KiCad/share/kicad/library/relays
LibName242=G:/softwares/KI CAD/KiCad/share/kicad/library/RF
LibName243=G:/softwares/KI CAD/KiCad/share/kicad/library/RF_AM_FM
LibName244=G:/softwares/KI CAD/KiCad/share/kicad/library/RF_Amplifier
LibName245=G:/softwares/KI CAD/KiCad/share/kicad/library/RF_Bluetooth
LibName246=G:/softwares/KI CAD/KiCad/share/kicad/library/RF_GPS
LibName247=G:/softwares/KI CAD/KiCad/share/kicad/library/RF_Mixer
LibName248=G:/softwares/KI CAD/KiCad/share/kicad/library/RF_Module
LibName249=G:/softwares/KI CAD/KiCad/share/kicad/library/RF_RFID
LibName250=G:/softwares/KI CAD/KiCad/share/kicad/library/RF_Switch
LibName251=G:/softwares/KI CAD/KiCad/share/kicad/library/RF_WiFi
LibName252=G:/softwares/KI CAD/KiCad/share/kicad/library/RF_ZigBee
LibName253=G:/softwares/KI CAD/KiCad/share/kicad/library/rfcom
LibName254=G:/softwares/KI CAD/KiCad/share/kicad/library/RFSolutions
LibName255=G:/softwares/KI CAD/KiCad/share/kicad/library/Sensor
LibName256=G:/softwares/KI CAD/KiCad/share/kicad/library/Sensor_Audio
LibName257=G:/softwares/KI CAD/KiCad/share/kicad/library/Sensor_Current
LibName258=G:/softwares/KI CAD/KiCad/share/kicad/library/Sensor_Gas
LibName259=G:/softwares/KI CAD/KiCad/share/kicad/library/Sensor_Humidity
LibName260=G:/softwares/KI CAD/KiCad/share/kicad/library/Sensor_Magnetic
LibName261=G:/softwares/KI CAD/KiCad/share/kicad/library/Sensor_Motion
LibName262=G:/softwares/KI CAD/KiCad/share/kicad/library/Sensor_Optical
LibName263=G:/softwares/KI CAD/KiCad/share/kicad/library/Sensor_Pressure
LibName264=G:/softwares/KI CAD/KiCad/share/kicad/library/Sensor_Proximity
LibName265=G:/softwares/KI CAD/KiCad/share/kicad/library/Sensor_Temperature
LibName266=G:/softwares/KI CAD/KiCad/share/kicad/library/Sensor_Touch
LibName267=G:/softwares/KI CAD/KiCad/share/kicad/library/Sensor_Voltage
LibName268=G:/softwares/KI CAD/KiCad/share/kicad/library/sensors
LibName269=G:/softwares/KI CAD/KiCad/share/kicad/library/silabs
LibName270=G:/softwares/KI CAD/KiCad/share/kicad/library/siliconi
LibName271=G:/softwares/KI CAD/KiCad/share/kicad/library/stm8
LibName272=G:/softwares/KI CAD/KiCad/share/kicad/library/stm32
LibName273=G:/softwares/KI CAD/KiCad/share/kicad/library/supertex
LibName274=G:/softwares/KI CAD/KiCad/share/kicad/library/Switch
LibName275=G:/softwares/KI CAD/KiCad/share/kicad/library/switches
LibName276=G:/softwares/KI CAD/KiCad/share/kicad/library/texas
LibName277=G:/softwares/KI CAD/KiCad/share/kicad/library/Timer
LibName278=G:/softwares/KI CAD/KiCad/share/kicad/library/Timer_PLL
LibName279=G:/softwares/KI CAD/KiCad/share/kicad/library/Timer_RTC
LibName280=G:/softwares/KI CAD/KiCad/share/kicad/library/transf
LibName281=G:/softwares/KI CAD/KiCad/share/kicad/library/Transformer
LibName282=G:/softwares/KI CAD/KiCad/share/kicad/library/Transistor_Array
LibName283=G:/softwares/KI CAD/KiCad/share/kicad/library/Transistor_BJT
LibName284=G:/softwares/KI CAD/KiCad/share/kicad/library/Transistor_FET
LibName285=G:/softwares/KI CAD/KiCad/share/kicad/library/Transistor_IGBT
LibName286=G:/softwares/KI CAD/KiCad/share/kicad/library/transistors
LibName287=G:/softwares/KI CAD/KiCad/share/kicad/library/triac_thyristor
LibName288=G:/softwares/KI CAD/KiCad/share/kicad/library/ttl_ieee
LibName289=G:/softwares/KI CAD/KiCad/share/kicad/library/Valve
LibName290=G:/softwares/KI CAD/KiCad/share/kicad/library/valves
LibName291=G:/softwares/KI CAD/KiCad/share/kicad/library/video
LibName292=G:/softwares/KI CAD/KiCad/share/kicad/library/wiznet
LibName293=G:/softwares/KI CAD/KiCad/share/kicad/library/Worldsemi
LibName294=G:/softwares/KI CAD/KiCad/share/kicad/library/Xicor
LibName295=G:/softwares/KI CAD/KiCad/share/kicad/library/xilinx
LibName296=G:/softwares/KI CAD/KiCad/share/kicad/library/zetex
LibName297=G:/softwares/KI CAD/KiCad/share/kicad/library/Zilog
